### Correlations 

```{r}
to_log("INFO", "Entering subsection 'Correlation'...")
```

The relation between all pairs of indices is given below.

<figure>
```{r,echo=FALSE, fig.retina=NULL, fig.width=5.5, fig.height=4.5, out.width=900, dpi=300}
d <- d_ind %>% 
    select_(.dots = c("OBJECTID", "HABITAT", indicators)) %>%
    mutate(id_chr = paste(OBJECTID, HABITAT, sep = "-")) %>%
    select_(.dots = c("id_chr", indicators)) %>%
    mutate(id_num = id_chr %>% match(sort(unique(id_chr)))) %>%
    mutate(id_num = factor(x = id_num, levels = sort(unique(id_num)), ordered = TRUE))

lut <- d %>% 
    select(id_num, id_chr) %>% 
    distinct %>%
    arrange(id_num)

# create combinations of color and shape
col_shp <- expand.grid(
    col = c("red", "deepskyblue", "orange", "green", "purple"),
    shp = c(16, 15, 17, 3, 4),
    stringsAsFactors = FALSE
)

g <- ggplot(data = d) +
    geom_point(
        mapping = aes_string(
            x = names(d)[2], 
            y = names(d)[3], 
            colour = "id_num",
            shape = "id_num"
        )
    ) +
    scale_color_manual(
        name = "",
        values = col_shp$col
    ) +
    scale_shape_manual(
        name = "",
        values = col_shp$shp
    )

print(g)

if (number_of_indicators == 3L) {
    g <- ggplot(data = d) +
        geom_point(
            mapping = aes_string(
                x = names(d)[2], 
                y = names(d)[4], 
            colour = "id_num",
            shape = "id_num"
        )
    ) +
    scale_color_manual(
        name = "",
        values = col_shp$col
    ) +
    scale_shape_manual(
        name = "",
        values = col_shp$shp
    )
    print(g)
    g <- ggplot(data = d) +
        geom_point(
            mapping = aes_string(
                x = names(d)[3], 
                y = names(d)[4], 
            colour = "id_num",
            shape = "id_num"
        )
    ) +
    scale_color_manual(
        name = "",
        values = col_shp$col
    ) +
    scale_shape_manual(
        name = "",
        values = col_shp$shp
    )
    print(g)
}
```
<figcaption>Scatter plots of all pairs of indices. The meaning of the numbers in the legend is: `r paste(lut$id_num, lut$id_chr, sep = " = ", collapse = "; ")`</figcaption>
</figure>
<br>
<br>

